name: Docker Build and Push - App

on:
  push:
    paths:
      - 'app/password_generator/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build
      run: |
        docker build -t praveenkumar081097/password-generator:$GITHUB_SHA .
        docker tag praveenkumar081097/password-generator:$GITHUB_SHA praveenkumar081097/password-generator:latest

    - name: docker push
      run: |
        docker push praveenkumar081097/password-generator:$GITHUB_SHA
        docker push praveenkumar081097/password-generator:latest
